####
POST http://localhost:8080/odata/v4/CatalogService/SaveBook
Content-Type: application/json

{
}

### Get Books
GET http://localhost:8080/odata/v4/CatalogService/Books


### Get Books
GET http://localhost:8080/odata/v4/cloud.sdk.capng/CapBusinessPartner

### Post Books via Action
POST http://localhost:8080/odata/v4/cloud.sdk.capng/CapBusinessPartner
Content-Type: application/json

{
    "ID" : "9999900A",
    "firstName" : "HAN",
    "surname" : "WOO",
    "sourceDestination" : "S4H"
}

### Get POrders
GET http://localhost:8080/odata/v4/CatalogService/POrders

### Post POrders via Action
POST http://localhost:8080/odata/v4/CatalogService/POrders
Content-Type: application/json

{
    "poid" : "12356",
    "potype" : "NB",
    "pogroup" : "001",
    "posupplier" : "17300001"

}


### Post Books via Action
POST http://localhost:8080/odata/v4/CatalogService/SaveBook
Content-Type: application/json

{
}

### Post Books via Action
POST http://localhost:8080/odata/v4/CatalogService/SaveBookTypesEntityProc
Content-Type: application/json

{
    "Books" :[ {
        "ID" : 1002,
        "title" : "test0001",
        "stock" : 12 
    }]
}


### Post Books via Action
POST http://localhost:8080/odata/v4/CatalogService/SaveBookTypesEntityProc
Content-Type: application/json

{
    "Books" :[ {
        "ID" : 1002,
        "title" : "test0001",
        "stock" : 12 
    }]
}

### Post Books via Action
POST http://localhost:8080/odata/v4/CatalogService/SaveBookSingleTypesEntity
Content-Type: application/json

{
        "ID" : 1002,
        "title" : "test0001",
        "stock" : 12 
}
